title = "The Fermyon Platform"
base_url = "http://localhost:3000"
about = ""

[extra]
copyright = "Fermyon"
github = "https://github.com/fermyon/installer"
twitter = "https://twitter.com/fermyontech"
ga_measurement_id = "G-HKF4WE7XF9"

date_style = "%B %e, %Y"
