name = "fermyon-dev"
spin_version = "1"
version = "0.1.0"
description = "The Fermyon Platform website."
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]
trigger = { type = "http", base = "/" }

[[component]]
source = "modules/bartholomew.wasm"
id = "bartholomew"
files = [ "content/**/*" , "templates/*", "scripts/*", "config/*"]
[component.trigger]
route = "/..."

[[component]]
source = "modules/spin_static_fs.wasm"
id = "fileserver"
files = [ { source = "static/", destination = "/" } ]
[component.trigger]
route = "/static/..."
